Admin > Feedback
Yiffer-xyz/yiffer.xyz-v3 pull request #41
Opened 2024-02-15 21:26 UTC by ErikMelton

Resolves https://linear.app/yifferxyz/issue/YIF-179/admin-feedback

2024-04-16 11:59 UTC, ragnarob requested changes
Yay! Works perfectly on mobile too, great! A few change requests, overall good stuff! We can remove the 🚧 from the sidebar, hehe.

2024-04-16 11:59 UTC, ragnarob commented on app/routes/admin.feedback-support/route.tsx
> +  const archiveFeedbackFetcher = useGoodFetcher({
maybe a `toastSuccessMessage` on the two fetchers? I made toasts actually work just now, oops

2024-04-16 11:59 UTC, ragnarob commented on app/routes/admin.feedback-support/route.tsx
> +      <div className="flex flex-row my-4">
The UI for this is a bit strange on hover, but it’s on me for not creating a toggleButton component. I’ll do so now, you can leave this as it is (or use mine if I beat you to it 😁)

2024-04-16 11:59 UTC, ragnarob commented on app/page-components/UserFeedback/FeedbackItem.tsx
> +    <div className="bg-white dark:bg-gray-300 rounded-lg shadow-lg p-4 flex flex-row justify-between">
I’d add a `gap-4` on this so the texts don’t touch the archive/delete buttons.

2024-04-16 11:59 UTC, ragnarob commented on app/page-components/UserFeedback/FeedbackItem.tsx
> +        <div className="text-white inline-block text-xs rounded-full px-3 py-0.5" style={{backgroundColor: getTypeColor(type)}}>
Maybe text-sm would be better? It’s a bit on the tiny side right now

2024-04-16 11:59 UTC, ragnarob commented on app/page-components/UserFeedback/FeedbackItem.tsx
> +  function getTypeColor(type: FeedbackType) {
A bit cleaner and more efficient if done via a `const typesToColors: Record<FeedbackType, string>` outside of the component function, and accessed via `typesToColors[type]` in the jsx. And no need for a default that'll never happen that way 🙌

2024-04-16 11:59 UTC, ragnarob commented on app/page-components/UserFeedback/FeedbackItem.tsx
> +  function getTypeText(type: FeedbackType) {
Same as the above, a Record outside the component instead of a func

2024-04-16 11:59 UTC, ragnarob commented on app/page-components/UserFeedback/FeedbackItem.tsx
> +          <a className="ml-1 text-blue-weak-200 dark:text-blue-strong-200" href={userLink}>
For the links, it’s important to use our own `Link` element instead of `a` so we avoid reloading the whole page. The Link has styling out of the box too 😁. I’d slap on an `IconRight={MdArrowForward}` on the Link too.

2024-04-16 11:59 UTC, ragnarob commented on app/page-components/UserFeedback/FeedbackItem.tsx
> +            {user.username || 'Unknown user'}
Instead of having a “dead link” for unknown users, I’d just put a normal p element for those, to make it clear.

2025-01-09 22:27 UTC, merged

2025-01-30 23:11 UTC, Dinoraptor101 commented
Magical, thank you!